<a href="https://colab.research.google.com/github/Alyssa-April/Data-Science-Projects/blob/main/NumPy_ndarray_Unary_Ufuncs_and_Binary_Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy ndarray Along with Examples of Unary Ufuncs and Binary Universal Functions

Examples of Basic Functions using NumPy

In [ ]:
# import NumPy
import numpy as np

### Generate Nine Arrays via Random Number

In [ ]:
# three 3x3 arrays
A = np.random.randn(3,3)
B = np.random.randn(3,3)
C = np.random.randn(3,3)

# three 5x5 arrays
D = np.random.randn(5,5)
E = np.random.randn(5,5)
F = np.random.randn(5,5)

# three 7x7 arrays
G = np.random.randn(7,7)
H = np.random.randn(7,7)
I = np.random.randn(7,7)

# make a list called "array" that contains all nine arrays
# this is to enable looping
arrays = {"A": A, "B": B, "C": C, "D": D, "E": E, "F": F, "G": G, "H": H, "I": I}

In [ ]:
# print out all nine arrays
for key, array in arrays.items():
    print("\n" + key + ":")
    print(array)


A:
[[-0.17263311 -0.08124047 -1.48360181]
 [ 0.58145194  0.63463757  0.59494205]
 [ 0.25962271  1.18859855 -1.61594891]]

B:
[[-1.49937982 -1.20293542 -1.29569073]
 [ 0.55467968 -0.17713913 -0.17376509]
 [ 0.74479637  0.82910188 -0.46996573]]

C:
[[-1.78199376  0.50023921 -0.96659305]
 [-1.19594319  0.39044657 -0.84879554]
 [-0.33253744  0.88805531 -0.65887162]]

D:
[[-3.13112479  0.88577617 -0.09045863  0.72153376  0.73465009]
 [-0.15501472  0.20769571  0.59712557  1.69321015 -0.59761699]
 [ 0.07861492  0.24478647 -2.83661741 -0.28129183  1.02455864]
 [ 0.69185089 -0.58325886  0.09666906  1.35006049  0.885639  ]
 [ 2.34071156 -1.09838848  0.664041    0.20573473 -2.38169019]]

E:
[[ 0.06937084 -0.37216436 -1.07722303 -0.73513857  0.70691537]
 [ 0.51316285  0.04130802 -1.15690715 -1.69849722  0.49740189]
 [ 0.49060675  0.27024329  0.19528674 -1.23077754  0.16352753]
 [ 0.81437583 -0.90471537  0.61661866 -2.66798622  0.82623122]
 [ 1.66007668  0.42611098 -0.92633579  0.9007563  -0.04482

### Table 4-3 : Unary ufuncs

##### 1. abs and sqrt

In [ ]:
# since we cannot find the square root of negative values, 
# we find their absolute values first before finding the square root
for key, array in arrays.items():
    print("\n" + key + ":")
    print(np.sqrt(np.abs(array)))


A:
[[0.41549141 0.28502714 1.21803194]
 [0.76252996 0.79664143 0.77132487]
 [0.50953185 1.09022867 1.27119979]]

B:
[[1.22449166 1.09678413 1.13828412]
 [0.74476821 0.42087899 0.4168514 ]
 [0.86301586 0.91055032 0.68554047]]

C:
[[1.33491339 0.70727591 0.98315464]
 [1.09359188 0.62485724 0.921301  ]
 [0.57666059 0.94236686 0.81170907]]

D:
[[1.76949846 0.94115683 0.30076341 0.84943143 0.85711731]
 [0.39371909 0.45573645 0.77273901 1.30123409 0.77305691]
 [0.28038352 0.49475901 1.68422606 0.53036952 1.01220484]
 [0.83177574 0.76371386 0.31091649 1.16192103 0.94108395]
 [1.52993842 1.04804031 0.81488711 0.4535799  1.54327256]]

E:
[[0.26338345 0.61005276 1.03789356 0.85740222 0.84078259]
 [0.71635386 0.20324374 1.07559618 1.30326407 0.70526725]
 [0.70043326 0.51984929 0.44191259 1.10940414 0.40438538]
 [0.90242774 0.95116527 0.7852507  1.63339714 0.90897262]
 [1.28843963 0.65277176 0.9624634  0.94908182 0.21171963]]

F:
[[0.25880384 1.0721547  1.26278081 0.85267235 1.55743246]
 [1.01586

#### 2. modf and exp

In [ ]:
# modf will return the fractional and integral parts of arrays as separate arrays
# if we want to access the fractional part, we can use indexing of [0]
# in this section, I compute the exponent of each element based on their fractional part
for key, array in arrays.items():
    print("\n" + key + ":")
    print(np.exp(np.modf(array)[0]))


A:
[[0.84144627 0.92197196 0.61655866]
 [1.78863354 1.88633835 1.81292589]
 [1.29644086 1.20755608 0.54012812]]

B:
[[0.60690694 0.81633096 0.74401749]
 [1.7413831  0.83766323 0.84049432]
 [2.10601255 2.29125998 0.62502369]]

C:
[[0.45749297 1.64911571 0.38037676]
 [0.82205893 1.47764051 0.42793005]
 [0.71710182 2.43039867 0.51743487]]

D:
[[0.87710832 2.42486578 0.91351213 2.05758663 2.08475238]
 [0.85640257 1.23083858 1.81688878 2.00012594 0.55012102]
 [1.08178766 1.27734854 0.43317329 0.75480803 1.02486269]
 [1.99740909 0.55807671 1.10149579 1.41915339 2.42453318]
 [1.40594765 0.90629675 1.94262665 1.22842729 0.68270653]]

E:
[[1.07183362 0.68924095 0.92568337 0.47943902 2.02772681]
 [1.67056659 1.04217306 0.85478342 0.49733212 1.64444327]
 [1.63330692 1.31028319 1.21565952 0.79391606 1.17765778]
 [2.25776599 0.40465705 1.85265298 0.51274008 2.284692  ]
 [1.93494071 1.5312907  0.39600209 2.46146401 0.9561646 ]]

F:
[[1.06927348 0.86112492 1.81233373 2.06896844 1.53050213]
 [1.03249

#### 3. sign

In [ ]:
# get the sign for each element in each array
# indicator:
# 1 --> positive
# 0 --> zero
# -1 --> negative

for key, array in arrays.items():
    print("\n" + key + ":")
    print(np.sign(array))


A:
[[-1. -1. -1.]
 [ 1.  1.  1.]
 [ 1.  1. -1.]]

B:
[[-1. -1. -1.]
 [ 1. -1. -1.]
 [ 1.  1. -1.]]

C:
[[-1.  1. -1.]
 [-1.  1. -1.]
 [-1.  1. -1.]]

D:
[[-1.  1. -1.  1.  1.]
 [-1.  1.  1.  1. -1.]
 [ 1.  1. -1. -1.  1.]
 [ 1. -1.  1.  1.  1.]
 [ 1. -1.  1.  1. -1.]]

E:
[[ 1. -1. -1. -1.  1.]
 [ 1.  1. -1. -1.  1.]
 [ 1.  1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1.]
 [ 1.  1. -1.  1. -1.]]

F:
[[ 1. -1.  1.  1.  1.]
 [ 1. -1.  1. -1. -1.]
 [ 1. -1. -1. -1. -1.]
 [-1.  1. -1.  1.  1.]
 [ 1.  1. -1.  1.  1.]]

G:
[[-1.  1.  1. -1.  1.  1.  1.]
 [ 1. -1.  1.  1.  1. -1.  1.]
 [ 1.  1.  1. -1. -1.  1. -1.]
 [-1. -1.  1. -1. -1. -1. -1.]
 [-1.  1.  1. -1. -1.  1.  1.]
 [-1.  1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  1. -1. -1. -1.]]

H:
[[ 1.  1. -1. -1. -1. -1.  1.]
 [ 1.  1. -1. -1.  1.  1.  1.]
 [ 1.  1.  1. -1.  1. -1.  1.]
 [-1. -1. -1.  1.  1. -1. -1.]
 [-1.  1.  1. -1.  1. -1.  1.]
 [-1.  1. -1.  1. -1.  1. -1.]
 [-1. -1.  1. -1.  1. -1. -1.]]

I:
[[-1.  1.  1. -1.  1.  1. -1.]
 [ 1. -1. -

#### 4. ceil

In [ ]:
# get the smallest integer greater than or equal to the element in each array
for key, array in arrays.items():
    print("\n" + key + ":")
    print(np.ceil(array))


A:
[[-0. -0. -1.]
 [ 1.  1.  1.]
 [ 1.  2. -1.]]

B:
[[-1. -1. -1.]
 [ 1. -0. -0.]
 [ 1.  1. -0.]]

C:
[[-1.  1. -0.]
 [-1.  1. -0.]
 [-0.  1. -0.]]

D:
[[-3.  1. -0.  1.  1.]
 [-0.  1.  1.  2. -0.]
 [ 1.  1. -2. -0.  2.]
 [ 1. -0.  1.  2.  1.]
 [ 3. -1.  1.  1. -2.]]

E:
[[ 1. -0. -1. -0.  1.]
 [ 1.  1. -1. -1.  1.]
 [ 1.  1.  1. -1.  1.]
 [ 1. -0.  1. -2.  1.]
 [ 2.  1. -0.  1. -0.]]

F:
[[ 1. -1.  2.  1.  3.]
 [ 2. -0.  2. -0. -1.]
 [ 1. -0. -0. -0. -0.]
 [-1.  1. -0.  1.  3.]
 [ 1.  1. -1.  1.  1.]]

G:
[[-0.  1.  1. -0.  1.  2.  2.]
 [ 1. -0.  1.  2.  2. -0.  2.]
 [ 1.  2.  2. -2. -0.  1. -0.]
 [-1. -0.  2. -0. -1. -0. -0.]
 [-0.  1.  1. -1. -0.  2.  2.]
 [-0.  1. -1. -0. -0. -2. -1.]
 [-0. -0. -1.  1. -0. -1. -1.]]

H:
[[ 1.  2. -2. -0. -0. -1.  2.]
 [ 2.  2. -0. -0.  1.  1.  1.]
 [ 1.  1.  1. -0.  1. -1.  2.]
 [-0. -0. -1.  1.  1. -1. -1.]
 [-0.  2.  1. -0.  2. -0.  1.]
 [-0.  1. -1.  2. -0.  1. -0.]
 [-0. -1.  1. -0.  2. -0. -1.]]

I:
[[-1.  1.  1. -1.  1.  2. -0.]
 [ 2. -1. -

#### 5. sin 

In [ ]:
# get the sin value of each element in the arrays
# the np.sin function gives the output in radians
# I print the values in degrees, by converting the 
# radians to degree using np.pi / 180. (as shown in calculator)
for key, array in arrays.items():
    print("\n" + key + ":")
    print(np.sin(array * np.pi / 180.))


A:
[[-0.00301301 -0.00141791 -0.02589084]
 [ 0.01014808  0.01107629  0.01038351]
 [ 0.00453126  0.02074347 -0.02819989]]

B:
[[-0.02616613 -0.02099364 -0.02261214]
 [ 0.00968084 -0.00309166 -0.00303277]
 [ 0.01299878  0.01447005 -0.00820236]]

C:
[[-0.03109664  0.00873071 -0.01686943]
 [-0.02087163  0.00681453 -0.01481373]
 [-0.00580384  0.01549887 -0.01149923]]

D:
[[-0.05462124  0.01545909 -0.0015788   0.01259281  0.01282171]
 [-0.00270551  0.00362497  0.01042162  0.02954779 -0.0104302 ]
 [ 0.00137209  0.00427232 -0.04948809 -0.00490945  0.01788097]
 [ 0.01207478 -0.01017961  0.00168719  0.02356082  0.0154567 ]
 [ 0.04084176 -0.01916932  0.01158944  0.00359074 -0.04155637]]

E:
[[ 0.00121075 -0.00649545 -0.01879998 -0.01283024  0.01233769]
 [ 0.00895626  0.00072096 -0.02019047 -0.02964003  0.00868119]
 [ 0.0085626   0.00471662  0.00340839 -0.02147947  0.00285409]
 [ 0.01421306 -0.01578961  0.01076182 -0.04654832  0.01441996]
 [ 0.02896975  0.00743697 -0.01616691  0.01572052 -0.00078

### Table 4-4: Binary Universal Functions

##### Since the functions are carried out element wise, the pair of arrays need to be of the same shape

#### 6. add and subtract 

In [ ]:
# example for 3x3 arrays
print("A + B:")
print(np.add(A,B))

# example for 5x5 arrays
print("\nD - E:")
print(np.subtract(D,E))

# example for 7x7 arrays
print("\nG + H - I")
print(np.subtract(np.add(G,H), I))

A + B:
[[-1.67201293 -1.28417589 -2.77929254]
 [ 1.13613163  0.45749844  0.42117697]
 [ 1.00441908  2.01770043 -2.08591465]]

D - E:
[[-3.20049563  1.25794054  0.98676441  1.45667232  0.02773472]
 [-0.66817757  0.16638769  1.75403273  3.39170737 -1.09501888]
 [-0.41199183 -0.02545681 -3.03190416  0.94948572  0.86103111]
 [-0.12252494  0.32145651 -0.51994959  4.01804671  0.05940778]
 [ 0.68063488 -1.52449946  1.59037679 -0.69502157 -2.33686499]]

G + H - I
[[ 1.4057147   1.75768391 -2.47458625  0.40801883 -0.66044296 -1.83529415
   2.84497655]
 [ 0.02848192  2.02038595  1.0396648   0.25055419  1.19552591  0.75810572
   2.74473369]
 [ 1.1110605   1.22219608  1.97952427 -2.95704368  0.01623354 -0.26684655
   0.65760894]
 [-2.90140771 -0.37631685  0.80954121  0.79056863 -0.49323081 -1.35886792
  -4.04897005]
 [-0.36105617  0.2421475   0.74957426 -1.99592148  1.23219192  1.85079205
   0.60316948]
 [-2.72740257  0.36456486 -1.99325053 -0.13078432 -0.92354516 -0.35326044
  -4.52985572]
 [-0.6

#### 7. multiply and divide

In [ ]:
# example for 3x3 arrays
print("A x C:")
print(np.multiply(A,C))

# example for 5x5 arrays
print("\nD / F:")
print(np.divide(D,F))

# example for 7x7 arrays
print("\nH x I / G")
print(np.divide(np.multiply(H,I), G))

A x C:
[[ 0.30763113 -0.04063967  1.4340392 ]
 [-0.69538349  0.24779206 -0.50498416]
 [-0.08633427  1.05554125  1.06470288]]

D / F:
[[-46.7475579   -0.77056466  -0.05672755   0.99241265   0.30287407]
 [ -0.15021101  -0.29243574   0.3357467   -7.43983651   0.44740368]
 [  0.08326136  -1.90095212   8.96869076   0.49812366  -1.78265714]
 [ -0.41445864  -1.17543023  -0.13150052   1.51303463   0.41206902]
 [  3.65744261  -6.00844337  -0.38195249   0.78541013  -7.63153326]]

H x I / G
[[ 1.33519076e+00  1.99510917e+00 -3.13841984e+01 -5.25405278e-01
  -6.11208611e-01 -1.93841087e+00 -2.02735811e-01]
 [ 8.18375160e+00  4.27576400e+00  4.21102432e-01 -6.82237310e-02
   3.49245385e-01  1.13784012e+01 -3.18474444e-01]
 [-8.86580308e-02  5.72466222e-01  1.22378608e-01  6.52747842e-02
   2.49331592e-01  9.51897650e-01  4.21853585e-01]
 [ 2.17109417e-01 -5.05498855e-01  2.12696586e-01  7.95037845e-01
   2.22775918e-01 -8.02605738e-01  3.28706250e+00]
 [-1.21223534e+00  2.23753723e+00 -6.06466956e-

#### 8. maximum and minimum

In [ ]:
# example for 3x3 arrays
print("Element-wise maximum of arrays B and C:")
print(np.maximum(B,C))

# example for 5x5 arrays
print("\nElement-wise maximum of arrays E and F:")
print(np.maximum(E,F))

# example for 7x7 arrays
print("\nElement-wise minimum of arrays G and I:")
print(np.minimum(G,I))

Element-wise maximum of arrays B and C:
[[-1.49937982  0.50023921 -0.96659305]
 [ 0.55467968  0.39044657 -0.17376509]
 [ 0.74479637  0.88805531 -0.46996573]]

Element-wise maximum of arrays E and F:
[[ 0.06937084 -0.37216436  1.59461537  0.72705014  2.42559587]
 [ 1.03197976  0.04130802  1.7785002  -0.22758701  0.49740189]
 [ 0.94419446  0.27024329  0.19528674 -0.56470281  0.16352753]
 [ 0.81437583  0.49620883  0.61661866  0.89228658  2.1492492 ]
 [ 1.66007668  0.42611098 -0.92633579  0.9007563   0.31208541]]

Element-wise minimum of arrays G and I:
[[-1.42183383  0.3369167   0.01872675 -1.11026617  0.1939659   1.11380903
  -0.2646657 ]
 [ 0.28477607 -1.02639429 -0.72770437  0.09445303  0.81097022 -0.44492498
  -1.0307829 ]
 [-0.13798001  1.07032658  0.17138107 -2.18329072 -0.96635937 -0.37926668
  -0.97378972]
 [-1.23664632 -0.53021155 -0.31460448 -0.76823224 -1.75393122 -0.4506927
  -0.79145761]
 [-0.8039387   0.87801086 -0.02195657 -1.02559518 -0.91037907 -0.92790641
   0.87352622]


#### 9. copysign

In [ ]:
# copy sign of values in second argument to values in first argument

# example for 3x3 arrays
print("Copy sign of C to A:")
print(np.copysign(A,C))

# example for 5x5 arrays
print("\nCopy sign of F to D:")
print(np.copysign(D,F))

# example for 7x7 arrays
print("\nCopy sign of I to G:")
print(np.copysign(G,I))

Copy sign of C to A:
[[-0.17263311  0.08124047 -1.48360181]
 [-0.58145194  0.63463757 -0.59494205]
 [-0.25962271  1.18859855 -1.61594891]]

Copy sign of F to D:
[[ 3.13112479 -0.88577617  0.09045863  0.72153376  0.73465009]
 [ 0.15501472 -0.20769571  0.59712557 -1.69321015 -0.59761699]
 [ 0.07861492 -0.24478647 -2.83661741 -0.28129183 -1.02455864]
 [-0.69185089  0.58325886 -0.09666906  1.35006049  0.885639  ]
 [ 2.34071156  1.09838848 -0.664041    0.20573473  2.38169019]]

Copy sign of I to G:
[[-0.26451877  0.3369167   0.01872675 -0.47667364  0.1939659   1.11380903
  -1.46109877]
 [ 0.28477607 -0.313977   -0.74042248  1.24238834  1.40250537 -0.01274452
  -1.30939526]
 [-0.5924233   1.4936442   1.25485043  2.18329072 -0.96635937 -0.42793568
  -0.97378972]
 [ 1.23664632 -0.46407936 -1.52794157 -0.64014739 -1.75393122 -0.4506927
   0.79145761]
 [-0.46453552  0.87801086 -0.57013853  1.02559518 -0.85331964 -1.02642198
   1.0150727 ]
 [ 0.6571714   0.70800858 -1.19231388  0.67004266  0.2675

#### 10. greater, less and equal

In [ ]:
# example for 3x3 arrays
print("Is C greater than B?")
print(np.greater(C,B))

# example for 5x5 arrays
print("\nIs F less than E?")
print(np.less(F,E))

# example for 7x7 arrays
print("\nIs H equal to I?")
print(np.equal(H,I))

Is C greater than B?
[[False  True  True]
 [False  True False]
 [False  True False]]

Is F less than E?
[[ True  True False False False]
 [False  True False False  True]
 [False  True  True False  True]
 [ True False  True False False]
 [ True  True  True  True False]]

Is H equal to I?
[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]
